name: cd
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build docker.pkg.github.com/sboardwell/dockerfile-for-dev-ci-image/dev-ci
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: dev-ci
          tag_semver: true
          registry: docker.pkg.github.com/sboardwell/dockerfile-for-dev-ci-image
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GLOBAL_TOKEN_FOR_GITHUB }}
      - name: Slack notification
        uses: homoluctus/slatify@v2.0.1
        if: always()
        with:
          type: ${{ job.status  }}
          job_name: dev-ci Docker Image Release
          channel: '#lib-robots'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GLOBAL_TOKEN_FOR_GITHUB }}
